language: node_js
sudo: required
services:
- docker
node_js:
- 6.7.0
install: 
- make
- npm i
script:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- npm run build &&
  docker build -t ${DOCKER_USER}/funds-front . &&
  docker push ${DOCKER_USER}/funds-front
- docker build -t ${DOCKER_USER}/funds-api ./src/ &&
  docker push ${DOCKER_USER}/funds-api
notifications:
  email: false
