language:
- go
- node_js
sudo: required
services:
- docker
go:
- 1.7
node_js:
- 6.7.0
cache:
  directories:
  - .node_modules/
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv -in deploy_rsa.enc -out deploy_rsa -d
install:
- make
- npm i
script: |
  npm run build &&
  docker build -t ${DOCKER_USER}/funds-front . &&
  docker build -t ${DOCKER_USER}/funds-api -f src/Dockerfile .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_USER}/funds-front && docker push ${DOCKER_USER}/funds-api
  fi
notifications:
  email: false
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "bash -s" 2>/dev/null -- < ./deploy.sh funds https://github.com/ViBiOh/funds-ob.git vibioh.fr
  on:
    branch: master
after_deploy:
  - |
    curl -H "X-Auth-Email: ${CLOUDFLARE_MAIL}" -H "X-Auth-Key: ${CLOUDFLARE_AUTH_KEY}" -H "Content-Type: application/json" -X DELETE https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache -d '{"purge_everything":true}'
