language: go
sudo: required
services:
- docker
go: 1.8
install:
- make
- nvm install node
- npm install -g npm
- npm i
- npm run build
script: |
  bash <(curl -s https://codecov.io/bash) &&
  docker build -t ${DOCKER_USER}/funds-front -f Dockerfile_front . &&
  docker build -t ${DOCKER_USER}/funds-api -f Dockerfile_api .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} && docker push ${DOCKER_USER}/funds-front && docker push ${DOCKER_USER}/funds-api
    sed -e "s|\${PERFORMANCE_URL}|${PERFORMANCE_URL}|g" -e "s|\${FUNDS_DATABASE_USER}|${FUNDS_DATABASE_USER}|g" -e "s|\${FUNDS_DATABASE_PASS}|${FUNDS_DATABASE_PASS}|g" -e "s|\${FUNDS_DATABASE_NAME}|${FUNDS_DATABASE_NAME}|g" docker-compose.yml > docker-compose-env.yml
  fi
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: curl -u ${DEPLOY_USER}:${DEPLOY_PASS} -X POST https://dashboard-api.vibioh.fr/containers/funds/ --data-binary @docker-compose-env.yml
  on:
    branch: master
