---
jobs:
  include:
    - stage: Build

      language: go
      go: 1.15
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - sudo systemctl restart docker
      script:
        - make
        - git --no-pager diff -- ':(exclude)go.sum' && git diff --quiet -- ':(exclude)go.sum'
        - curl -q -sSL --max-time 30 -o cacert.pem https://curl.haxx.se/ca/cacert.pem
        - curl -q -sSL --max-time 30 -o zoneinfo.zip https://raw.githubusercontent.com/golang/go/master/lib/time/zoneinfo.zip
        - curl -q -sSL --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "release"
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - ./scripts/release build
        - DOCKER_IMAGE="${DOCKER_USER}/$(make name)-api" IMAGE_VERSION="$(make version)" DOCKERFILE=Dockerfile_api ./scripts/release docker
        - DOCKER_IMAGE="${DOCKER_USER}/$(make name)-notifier" IMAGE_VERSION="$(make version)" DOCKERFILE=Dockerfile_notifier ./scripts/release docker

    - stage: Build
      language: node_js
      node_js: 14
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        - sudo systemctl restart docker
      script:
        - npm run format
        - npm run style
        - npm run test
        - npm run build
        - ./remove_hash_from_asset.js "$(make version)"
        - git --no-pager diff && git diff --quiet
        - curl -q -sSL --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "release"
        - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
        - DOCKER_IMAGE="${DOCKER_USER}/$(make name)-ui" IMAGE_VERSION="$(make version)" DOCKERFILE=Dockerfile_ui ./scripts/release docker

    - stage: Publish

      language: minimal
      script:
        - export APP_NAME="$(make name)"
        - export APP_VERSION="$(make version)"
        - curl -q -sSL --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
        - scripts/docker_promote "${DOCKER_USER}/${APP_NAME}-api" "$(make version)"
        - scripts/docker_promote "${DOCKER_USER}/${APP_NAME}-notifier" "$(make version)"
        - scripts/docker_promote "${DOCKER_USER}/${APP_NAME}-ui" "$(make version)"
      after_success:
        - curl -q -sSL --max-time 30 -X POST https://goreportcard.com/checks?repo=github.com/${TRAVIS_REPO_SLUG}
        - curl -q -sSL --max-time 30 -X POST --data-urlencode "gitUrl=git@github.com:${TRAVIS_REPO_SLUG}.git" https://doc.esdoc.org/api/create

stages:
  - Build
  - name: Publish
    if: branch = master && type = push

notifications:
  email: false
