language: go
sudo: required
services:
- docker
go: 1.9
install:
- make
- nvm install 8
- npm install -g npm
- npm i
- npm run build
script: |
  bash <(curl -s https://codecov.io/bash) &&
  curl -o zoneinfo.zip https://raw.githubusercontent.com/golang/go/master/lib/time/zoneinfo.zip &&
  docker build -t ${DOCKER_USER}/funds-notifier -f Dockerfile_notifier . &&
  docker build -t ${DOCKER_USER}/funds-front -f Dockerfile_front . &&
  docker build -t ${DOCKER_USER}/funds-api -f Dockerfile_api .
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} \
      && docker push ${DOCKER_USER}/funds-notifier \
      && docker push ${DOCKER_USER}/funds-front \
      && docker push ${DOCKER_USER}/funds-api

    sed \
      -e "s|\${PERFORMANCE_URL}|${PERFORMANCE_URL}|g" \
      -e "s|\${FUNDS_DATABASE_DIR}|${FUNDS_DATABASE_DIR}|g" \
      -e "s|\${FUNDS_DATABASE_PASS}|${FUNDS_DATABASE_PASS}|g" \
      -e "s|\${MAILJET_APIKEY_PUBLIC}|${MAILJET_APIKEY_PUBLIC}|g" \
      -e "s|\${MAILJET_APIKEY_PRIVATE}|${MAILJET_APIKEY_PRIVATE}|g" \
      -e "s|\${FUNDS_NOTIFICATION_RECIPIENTS}|${FUNDS_NOTIFICATION_RECIPIENTS}|g" \
      docker-compose.yml > docker-compose-env.yml
  fi
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/funds/ --data-binary @docker-compose-env.yml"
  on:
    branch: master
