jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg CODECOV_TOKEN --build-arg "APP_VERSION=$(make version)" -t "vibioh/$(make name)-api:$(make version)" -f Dockerfile_api .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker push "vibioh/$(make name)-api:$(make version)"

  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build -t "vibioh/$(make name)-notifier:$(make version)" -f Dockerfile_notifier .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker push "vibioh/$(make name)-notifier:$(make version)"

  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build --build-arg "APP_VERSION=$(make version)" -t "vibioh/$(make name)-ui:$(make version)" -f Dockerfile_ui .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker push "vibioh/$(make name)-ui:$(make version)"

  - stage: Publish

    sudo: required
    services:
    - docker
    script:
    - echo "${DOCKER_PASS}" | docker login -u vibioh --password-stdin
    - docker pull "vibioh/$(make name)-api:$(make version)"
    - docker tag "vibioh/$(make name)-api:$(make version)" "vibioh/$(make name)-api:latest"
    - docker push "vibioh/$(make name)-api:latest"
    - docker pull "vibioh/$(make name)-notifier:$(make version)"
    - docker tag "vibioh/$(make name)-notifier:$(make version)" "vibioh/$(make name)-notifier:latest"
    - docker push "vibioh/$(make name)-notifier:latest"
    - docker pull "vibioh/$(make name)-ui:$(make version)"
    - docker tag "vibioh/$(make name)-ui:$(make version)" "vibioh/$(make name)-ui:latest"
    - docker push "vibioh/$(make name)-ui:latest"
    after_success:
    - curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/funds
    - curl -X POST --data-urlencode "gitUrl=git@github.com:ViBiOh/dashboard.git" https://doc.esdoc.org/api/create

  - stage: Deploy

    script: |
      sed \
        -e "s|\${PERFORMANCE_URL}|${PERFORMANCE_URL}|g" \
        -e "s|\${FUNDS_DATABASE_HOST}|${FUNDS_DATABASE_HOST}|g" \
        -e "s|\${FUNDS_DATABASE_USER}|${FUNDS_DATABASE_USER}|g" \
        -e "s|\${FUNDS_DATABASE_PASS}|${FUNDS_DATABASE_PASS}|g" \
        -e "s|\${FUNDS_DATABASE_NAME}|${FUNDS_DATABASE_NAME}|g" \
        -e "s|\${FUNDS_NOTIFICATION_RECIPIENTS}|${FUNDS_NOTIFICATION_RECIPIENTS}|g" \
        -e "s|\${MAILER_USER}|${MAILER_USER}|g" \
        -e "s|\${MAILER_PASS}|${MAILER_PASS}|g" \
        -e "s|\${ENVIRONMENT}|prod|g" \
        -e "s|\${COMMIT_SHA}|$(make version)|g" \
        -e "s|\\\$|\$\$|g" \
        docker-compose.yml > docker-compose-env.yml
    deploy:
      provider: script
      skip_cleanup: true
      script: bash script/deploy "https://deploy.vibioh.fr/$(make name)/$(make version)" "@docker-compose-env.yml"

stages:
  - Build
  - name: Publish
    if: branch = master
  - name: Deploy
    if: branch = master

notifications:
  email: false
