FROM node:11 as builder

ARG CODECOV_TOKEN
WORKDIR /usr/src/app
COPY . .

RUN make funds-ui \
 && curl -s https://codecov.io/bash | bash

FROM vibioh/viws:light

ARG APP_VERSION
ENV VERSION=${APP_VERSION}
COPY --from=builder /usr/src/app/build/ /www/
