FROM golang:1.12 as builder

ENV APP_NAME funds

WORKDIR /app
COPY . .

RUN make ${APP_NAME}-api \
 && curl -s -o /app/cacert.pem https://curl.haxx.se/ca/cacert.pem

FROM scratch

ENV APP_NAME funds
HEALTHCHECK --retries=10 CMD [ "/funds-api", "-url", "http://localhost:1080/health" ]

EXPOSE 1080
ENTRYPOINT [ "/funds-api" ]

COPY --from=builder /app/cacert.pem /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /app/bin/${APP_NAME}-api /
