FROM node:12 as builder

WORKDIR /usr/src/app
COPY . .

RUN npm ci \
 && npm test \
 && npm run build

ARG CODECOV_TOKEN
RUN curl -s https://codecov.io/bash | bash

FROM vibioh/viws:light

ARG APP_VERSION
ENV VERSION=${APP_VERSION}
COPY --from=builder /usr/src/app/build/ /www/
