FROM vibioh/scratch as api

ENV ZONEINFO zoneinfo.zip
EXPOSE 1080

ENV API_PORT 1080

HEALTHCHECK --retries=10 CMD [ "/api", "-url", "http://localhost:1080/health" ]
ENTRYPOINT [ "/api" ]

ARG VERSION
ENV VERSION=${VERSION}

ARG TARGETOS
ARG TARGETARCH

COPY cacert.pem /etc/ssl/certs/ca-certificates.crt
COPY zoneinfo.zip /
COPY release/api_${TARGETOS}_${TARGETARCH} /api

