[[constraint]]
  name = "github.com/NYTimes/gziphandler"
  version = "1.0.1"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/httputils"

[prune]
  go-tests = true
  unused-packages = true
