apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-api
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.84'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds-api
    image:
      name: vibioh/funds-api
      tag: '202207101532' # {"$imagepolicy": "default:flux-funds-api:tag"}
    config:
      API_DB_HOST: funds-db
      API_DB_NAME: funds
      API_DB_PORT: '80'
      API_DB_USER: funds
      API_LOGGER_JSON: 'true'
      API_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: funds
    readinessProbePath: /ready
    secrets:
      API_DB_PASS: AgBpjzGnmrqY3jYLbFfN3PFhJ+Bmydez2Zj7reevX9Im6+CXJRj6T/1wSR88Fvb+LlEvdanN3GsAHifjIGz0gVJaHIQ6/rRIFegc138kdJtCjI3gYW+AyISkYknYk5Fqdswu5L9ZHwQls3CfneLg/AVniXoPmSh5t2CEECKETVSsB+msKH/tPrSrRx+DgH6HM2wzovncR/EzT9hNfbvEZSOAfe0Si0WpS9ZUskE4S0nXiql1oW/yt7jG6eV+0F9fsoWEz+1a+WEMjfezt12MMCyFghlAx1Iv1rJA48bC5mBLkPA8yQSTimFZufQ67AJjz1m6sB0ZMdR058CVfMVbikGyx+ePzWfi3g4qoMtqtUhsIXAG7k+t9g5k+zzF/97Me9jlPsI63k2t3vrcZMxhNKDkZaqIrYpNIazSAKRE3Bz/j0skhviv+lP5ZiYfIW2VXusscAcbZZPppwMHZWA5o/hMm1dzdM6lkj+d/FJzNdRDpgeOefDzwKt6c4MxGkuM23xL0q0dJqwxnPjg7Pw8NkRd1rOWMlLNNjkoxWQv9FVsZh3uMhA7MdGXL7aL3NwoRyIvz0yPWHLLZP56Dk1xbj/llDC1VdN7eJbJBcqTDaRckCtyP3pD2r6B2E5uRd0PXGueTLzVF74ETr6iA2d2/jECekjWjf8U0sYfIScqjEx2Ap4ssotuJElmTdvfpH7oFVKsez8C5mPG7qLA1oBXQ78TrIbJ7kuGYDrYX8QSuBhpdltXRXXMKyx1TO+MkByU53In9Pi4Ab6QgEsCZf8=
      API_INFOS: AgAAQO9sEHI8PzfYNc5TyROybJqPDbMCv+tKaFMNPXATX+vQZCHdVaEyUWYyTzVHMIntzp3CBTkNR5R3Lfu5Yb18ueK1ShJP5gsslL0QtQgwwlF++GpqCcy1KAbOlo/fkiuEljrQ3cTLAVhnuJDzWCr3pHyqrZslJhfmNvOkI+yeiJSqZZwHBxqqVaHthvnvK01xp6hbFDzmu1Yr6SAw+ZIgP68pPhCiEK1jhoouWgSp0JgVLEXDLz2R9AO31tdCQljOVBR07ZH+K3IudV/6QWD8LziOrhtOj6+KMcYLrFtZg9ePhDN7bYmCwL82EUkzod1vGRpb5ZP9ZVWK2KuhA1fR6cQRY6NDkGtGjjBp84M2ljInJtHB3VXMbfDEPYSwYCXr8CcGpWuFRX6h4NO0TEBwGewO9tWypNzb65wfqPCdqe31EsNLbSM6F5XAfnn9447EHZfr/YwAYsfSKRAMerlyNqmUgYXQ+dnvH2811xCEVSUWJQiuG7tOR23/MgZJkTWHCRy7vNuuS5fWuEj1RAc8t6NFBeMZDFxBQwMuTfL5sxCDTo0VZYFuxif8Xs1lhrej/guZMon/u09PXHNfZb1bxnSNmSzDiTNMx8HgGsxhB4NP1uK12uf8F1/UITl9AjGn+XbFc5pICukviHJ7B/P/bBdcThOYGn5fFDT12MJE0bAj9tS/loBuDX4Nu6mabHR0vUiZ9j6ySCAdddhMKWpTiExxWJDdnbyznmMXiYXnIMVTIe5cGwsXI3V1kpKD1yoNI/0V9QDWlgrcwz8K6Q==
    ingress:
      enabled: true
      hosts:
        - funds-api.vibioh.fr
    pprof:
      enabled: true
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - funds-db
              topologyKey: 'kubernetes.io/hostname'
