apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-api
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.81'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds-api
    image:
      name: vibioh/funds-api
      tag: '202204250738' # {"$imagepolicy": "default:flux-funds-api:tag"}
    config:
      API_DB_HOST: funds-db
      API_DB_NAME: funds
      API_DB_PORT: '80'
      API_DB_USER: funds
      API_LOGGER_JSON: 'true'
      API_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: funds
    readinessProbePath: /ready
    secrets:
      API_DB_PASS: AgB63wjQEP9tWVvK/6wXKBDgeM5Or2o9hTPoeOglrWGNnV0bIXeEGGTn+bwHu7IHpycZWCQEO0YDLWo9OLOKstAnl2HWhnyS9wulaiHVb9WNSDjSmgW+b0M6MIB4zzim+3SrXGY8U5+8DSleZRDGU3ja89ts+jZZveDN35qY0Siip0CkD5ebjCM9hzR+xsqW1TImtpkZFyeygmNcgcsn5MSUR5iwXViZutaOpCiKU6kyjDGkzoDKdTOeHzj8ZxXyTWy9Y4P31L+dWaBRAsvGj3uv8NmOq09NZfafdOd2fDF7Iur00QjfXNuxGgRP208hyS4G1v7MQ3LGWq/z9cW/zvPzHyQDqf60Wn8EllbX1AyB+bAk+ZXdSPT8P9UKrof7NjQKU/apkmXpr3IhRzKRbjkUf+DpoBe2dK6Ghk7FopExu1J2RQOoDcBapPX3R3/Sa0BVKA34xiKfdap5Ri+dXMqCwaSd0rH+dVVf6xbdE6tZf6CgOQp6uXkuEH5Er5CxbLyqfH8LeDFHgA1RDlhDbD3X2WIza5XMmeXlyfZGL4EPCcZsLgtqPq6T0bHK+clKw+1wbfa36cEy/fkRzo5E9m26DLNkEjnDS5p60JtewTiLxzLWeMd0dzPShBoHduQAbxzwSV0A0eUPOMKAt6wDsemW7NDc04HP3MFELiwd1JcB1k3NEPVryx0EEN/ZVRqpXHkkRfTeaq93xMIk7KlWuyct1sgki/RXF1eo9oZlKep9MsUx4KRCX6Ha9+B15KzwE16oY9S/WP7pHXBDqPA=
      API_INFOS: AgCA0dvHbVg4GxEsZrHQPOECV+F6IkNDYkesXCPiKNGeIbQdFs4ZR54LEiRWZ9EGjqiDTVVp9NJBD40se5wXpNOXnhUXaHbGeLJi+Yz6rE/OOEMMQ7yxSnv9r9gF00hBnV/NN9TIBwto2Qae2SldR5lM5SNeCUPRqOGOXC0psk77SLpYFC7dhrKJ0JmwJyoUIuAUX5rUafGoUql1q6gHJAJatC5+tDbzCHSRyzgbuBzN8Zz11Q5F2jcuUtdPOx/yA8GjCZZsi0f2tECZgnnmFF5yQk1kdh3gz4Cfzq1ThN5+EoISk6P9F2AONim0Q9cNG806r24OVhLkKTofBKV0ZU4JhKheroAuLQuMlbQrjuHeL5UAbVrXLAOv6PCPeVnUt2i7kxIEVh8smkwCmOB4P9GymeZrrA1FCZiSXdtTv8/QdKA2RFDJ0aEnohTaxwMDBQAwYXYeJWlJI8GE/0g3005sOmkXd0b2qt1fL3aLVxAwaOnMLWx/FfNnbccDXSXv448ySswwqvLwIyd075rTu1s/bXUwBGMDnw2ix2OgPgTtF96P2shmwi3c5i75KmU2zWened1lRihKdtKJUAL95aQUAwQ1Kxu8pn01/6lAFT0Qz483mdbNKT/Un9XhVyX6bIU75p1Rtc341s4MFsCVKmPQi9Po6mlIQIfBx5RRkxjFg7L8m+0XC/Z0iuYXlt2qpITfDHxLDfZxfyScK9djzYHs5+4eSSBzb6Py+pqGN8xeLxc35R5EWFH7Qz6CuuN+BL3ARas2EFVOqJ2myUAUCg==
    ingress:
      enabled: true
      hosts:
      - funds-api.vibioh.fr
    pprof:
      enabled: true
