---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-api
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.27'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m

  values:
    nameOverride: funds-api

    image:
      repository: vibioh/funds-api

    config:
      API_LOGGER_JSON: 'true'

    readinessProbePath: /ready

    secrets:
      API_DB_HOST: AgAd1ttHL2X4bYq6vCmPAH1DXoyhzO3BsGo4NeDegw2EQ57X1WQY3X0FBTItHIRDlEyUSWyiR9Qdd6i8WWYBK0+9clXClWy3pOWLKaTSAXbrFLzZRgK16IPxoJsnyyUVixV9R3iict1pdfP9/XurlPOkYS+P3FxlTmfPUOqvMnkg1tlfrnGUeI0QV8Z3bpsF04P+HGPSQCGQ7VMJmEPwuLmIYaMD90Sl9eDXBWPJJ36ujrd8rPvP5NPpzyNZ52SLcgLwIdJvO6mc2H5DGX6Ui1p1tmgM19TAho970D2iLQ2DZuo8Bx5zEvoOo05i7Dmjm+5pIQOztWAhtphcAMotGdrAmRjjpHfA950kVtdM+p2RpvpV7IYt2NmUGQUTqVSoIEscf4KDCSjrQ6/PEVRkm+r3aNqzQFxGnXWQZPgb9uehcZsop1f9penraVHteGO4JFJPrU6Ah1KobhgI8eNG/oFlFGAq5BocW8i140DdTMqWWXcGdAMwbh2Sk+kEpgSpzQsiy67KbGwCqoouKh2R3BxAEjTphJ21DN57mm078JSsgyMpsvwn+8JTcQvYW4wFbw2lnDezdRBFSzmoeeJnSPO7uek01vT5TT9rigYAwGTexu5Xh/AK0+CjdZ1nPs/vEnV9qOMLJMJRM/9z1lSkO4MMQqy2tILhBmrcZqLQqCMRTlX/OxCrUsY7JRV2k/NSFL0+TKOLDQm3GT60bPnpa28eVyCCEufW
      API_DB_NAME: AgCdjYF1PiYMTueb284csWhdxPpmlOVfFlJxSJhqR4bs9NoGvKdBNE+vLm17cZzBPlYT8Vnvk78LZu29LBDpvr2jPOr7QKSZCwyEm0y0k2TLSHa2LgpPO+OqGd7PCOAxXk56IZlN+LQTLM0FfRJpOUUhFCsmCgWxXqtruYgI4hTRlxkjT8JCgPJQ0Mlw2v/sCERmB7zO1xS3E/tZehQ5XEdqROb/LxSp0iEPmvfczrh5eXKMuYX5VKQp5vc+quYPzOke5ekptPxzMQhnS7f7xMlB6MueXlidrEfUEtfj8D9vThM3tfWkstqOMGt22xEw2lznjkOyxDdMNN4X5c5SKOkBrpV4eRr5xr8Gxp98J8RfHheQcUkRcPLbwSOFvsDNLloQmGlu+ciZG5Ljjv8aX+00LJaLqGN2WHxsj4O4tyrsb7cecf0w9LqPcknjXR9bfrZ23NH7M+GdWIsxjvGq5QRnfr3+7uXxyn2g32pKcHELxqTXuGzAfvY9HHz/5DhfRiSauZmHG3UCxPCHEb9rgGOCCf3KjrBPqyVdN6gkM7Qu8LsBYr3bK/usi1z2ONMvke5Ca+2eC5kSIq4fOMBX6hYIz+PBiVmQOKqKE0192A6uScyzfMpgSShXkjJh1bxaPoqAYLc671WSkwciTTmZC89nIYNpOaAe+ypC07fbY1s+J4LMXdMtntNiQiZfdAJFy4Nc8Jx5KpizCg==
      API_DB_PASS: AgCujnxU3lq27pfubR/8KdX70ERzGMvWSZMgNxzt/vKzLHqI3IUoGKYnwVMokFVjMDbsH54o8DlIuRJbb8khW4btMAqAgUuS3SxmQi3Dy4BFAPkscexoVIOPSXdKdY8haXE1EmClhrmNCMHkPbLbAwJ1E6lAAl1pAKE+jvkHn1H7Z5GraSepsEtrIzevl9VLCe6LZLleFfjxYIZGRl4BBAFwMpOBT+Ssnjnnh0aDgUiohe0Flm3fM6IOQmGQf101EBIru2EOIweaXuuz5w4LwUzipTNcjg+T9+W/45zVDqxItUXw6gC96iDYL5fu+RJzMVIHjdQxPHIH2gI+6R9RsD/ceaekF0RdncBLyeMipP9dk6iSEAZVeSLDiH9esjG36cxLdza9uwec5ATa+8N0/Rnxez7wvL1ds/WUSjf0B+BZ6/PhlZARtlreWbqHhrr6cm2uIKRLduAcPsP/5QSN/PcpKWM9lKF974nLSYZ85zyq8Ozq4AzA34KlnmJkv/I85K63xDb4k/ECiWZQRt8GLmYpFgTnrd/jENPkYTrUjRVUHSbfPdz3zEWxScmPB9mOZB0uHECK2OahtQx/FrVz/j6IMlgRfeFYNh+VQ+lngFWu8pHp4g+mAJAvvTKnIOeJeoYMBbArUYUpywo4zt9rA45gGvMynL8rhS4DnLcb7IyI6Lfj0CHsBVHmXAp6JxGK4vwUxJ+k7HNkZ2wIGEeWIzlFFrIpYw2Fd9EUzma5vJq5rA==
      API_DB_USER: AgB/DAadyjBOq/cZOqxmoPM1GRytVzyBpLzwuTk9m1b3mrILRluKBF8/TAJdnr4Vn6woBas60l1Ldw8c8qiiOQRv5ghS7rRMFqk2KObkucTuL//0j4NiO3rf9ERKv7+jqsPovchtQb6gtPr4HF7/hJagngpF6Aoz+uTOxP2IMYMt+UsmLuWY5qCRs8qEntK2PKtBYkGH5JmWs6brv7RfqYYhKfdqlWKT4MzuphUi7BRhQbNfIHED0UE6PeyzDipPLqH+Gfc+HH1jldirA7829Nf2YaShUYqOz79zIjdwVXpCn6SUkb7QulZte9ntojNfVzVq8SvjwSlGoMTxDNcfvowy+cCbJpRcwGdZyUdxxnoD359LyHEx92RGlH70+nIkyPwhXHBAUVr00MHpK1H5z0MmBtK7hZR79i2R3szPOXsUvOE1h/4nfUpgkL/EXMv1qP5r2IcqK3F6hE7V2vIiL95LPoJkHLw/vEXEX1208Q7v67eKPn1LEpAdW2X2N2o5V4qgcWauiSfWNgV4HWDDcxWcrS5LBwP673wDzVwYzXSYGntkuX5a7JjxBD4bhgUQBENm848n/iOF83mUo9FA3SO9jY4BzM93oJN7Y/gyJT7iMXl51PIURtowloWTsPFcEjEB6xxbm0/Qzcm8VCF6u6sXurZcCKbW5UdfKdg+5rUbInYVy3EHwTml8Vc7rRwVnYt+Z676HhibgQ==
      API_INFOS: AgBhyCHxSwLIJY6fy8jsbnFHq1ecmUkgKPQX672jxyeQeJpL2aLQzBKDrhICM3I2gaGRzLGRq6PjPt+qLJFHw2qlcQLw8FzdOX9gqOQiv844r3e6GUJdm8Kvz+AQbS1XXSsmzwF8EPJJz7zH1EqznGfHhJUIhM4oNsTlIOK11TYVP13jnsIradlkOvseAHniTFrNMcxO8vyk2QP3tCUFEuASr1N1IF4FLvmv+0Z4KSZcPE18kkDTHL8yIOCZK0qyAAJzoiAx/NOifMKrpia6xpFJXGkwraU+my6W0nsTjCLHj+i90lpf+JIog4q9Ey6jeByA+sduzOgIwABVehP5SbjxJ3+B6IyTuU/dljTvsE07C/gL8WiZGeIjj+Yqb0p7bDYdtk9e2T/72MI0708SX/QGS4uq+4BWgE0e2zZdlajr1yQosfuV5dCapKk2v76BF7BGXipfzU5NX2TAd2pzVp/CDz5hQnlKrUw8Xcjd2r6AWSiu64ku9ODdM4N/pqdkT7L7f0TZx/cLuZ56YB0eiZmdk+YFGqHTNm28oyp73l0JBFcT9/wN85/CICahJn/Q321FFNk/B4Md5aiayDbwvtFU3JPOxcaT1sbffkGGinKLvAqWblpAI8Aqf///NAVrcVa9JVh5aPpYMSuE2klOkZxm+vPijIqMZqJhxlmjcJAjQTSO8rMgz0ybYlGTG0rFPZD7qnb0i1O4LIolS9+wgHIX596a7FZSFEfqesZ9hj22IwNNYB6pVV9Rl0xzvaYQ16Us8NJuh6f2InWzybQvDw==

    ingress:
      enabled: true
      hosts:
        - funds-api.vibioh.fr

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: '0.0.12'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m

  values:
    nameOverride: funds-db
    config:
      POSTGRES_USER: funds
      POSTGRES_DB: funds
    secrets:
      POSTGRES_PASSWORD: AgAxk/7hXQjutcydu6zcin5GIs5884wb9TfZeZmkvR6ZtZcjiWGkdb84c0AqdWY6TYGPH/JThzf8w9zJhTUWNE2LYfkTluaHwXHwBz9q+qq/BRM2kI87lNLJJToegNWZM6tnNO+fRxe+G7PI71Viv7I4aIPvPaS4kD6MN4/xHSjwXGxeRHFoayqFCOWUYcpqsxGQuMvW/NGtddjOBcd+zn2ZUet+NXhmHGfNLX/m/YYEfkWZGqSQ7gtMz5O9Z/BN/frJ8ry72dIlTQCd06/BamAW8Sgv5oQ41US4NRaDEVpMp8BqZMCCJuerbqp4zrvuqV+cqMgv/48KLYFX9tP8fNOMsJCetzzJ3KgbXSYAuBhWMnjaBm+J9fQRHq7ZIyo0N37ncDadAjgmGLAJUZKCfgluHI3A8a2c5OaElJPMYJunu50S+CWMQBL6ELqTOImqKIl0pP7GRt3N4wrGkFncP7Uw6gj+tg/NJ9fYVkqNp1/fCdQmk2bwWi3yV30Slkgfyudmb7bD36ow4wRmNjyemKO7KgsNln7pGSl8s54IT2BjffS62Qoy6KCPTNLP19FjkXtECtlbeOoG5XE0TfUj+xZ+NsMfLLfNmqCJ5GTZV49UhGm7Ba9ZH2H0FxROxT1kFMXUtjXcJg+hVVB1tHFdMkhr8uO8zTjU3LqLW19tLOvpbkS0bYvRzVXb8omoDiGtaMVb7KW+bc/bw6udmMMgSRkltkmDU+B8dI9k+OjepJMPkzKczUgQAT+Xc5eGFxH1E37RTGfHdiWeoXMLOFc=
      FIBR_BACKUP_PASSWORD: AgDJL16rh62Y0BOXBc1oq5+58lLGSQEiH4NfmvpfuO1uXmV0OUpHlI5oP3ikmBse8SI39c3ZzoRIjMKRJVtfz5ZwHbK30fxSVHOFiN8+knvAO8wyUmBXh87wQ/U15+2+/efYVb5Lw28vWITZZzewPFCUEUDXiuJ0fWtpCMxNReFT0TB54sv7p1+HPzzv/XHu2qxGpi+ar169XsK8bK1qdrbm9zjBUttVxnzFOxGV4R/ebJCOGSpC8DuRsaUxfv26b8Rf5yhCtEGwayheqyYKaqXTK4hQgoNrCQh0mWjoZBkAlbi6HKUB0N5MGrRJiieJv5/pnXksKAihYIZsthe17tHJKEIy07YorgyALUQ1LRkDVfTTtHLM4r43sPQIpmEDCT/n/nd5P+h7swVuAa8wb4a4o4qZITDtIHl9IpOFs9tvw5kdhuWWdpywIgH23vae6SN31b0YednGvFVVzjU2qL4G929FUZiRPr3lXUwZGdHLdXT9oFc4usDNsARgmrKWqDZSSp8dR7bdtYv1t+wlMoUnnomCiod+2kh3BKVCTTC+WetjVKdMyB8uouavYuCxj2iXIEL1ik1hVgQOIiCRabYFFD0z1rlJEhZl/+orCg8kG1HF5jK3W10gYpsLKPfEYalHt7CHU4R0LUiCSn7z+XqTxMJAu64ZmdcGR2Cc1sI3eXkMIqBa52PnpuBM2MzlT9DCPktfiS4a+7nO8/DOFdV4l0Ggb4atioAvVTb/jmkfVleJk+4g2hEv4+G54oEVSFhawjcnFvV5ADkWFCU=
