apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: '0.0.25'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds-notifier
    jobLabels:
      k8s-cleaner: 'true'
    schedule: '0 8 * * *'
    image:
      name: vibioh/funds-api
      tag: '202207101532' # {"$imagepolicy": "default:flux-funds-api:tag"}
    config:
      NOTIFIER_SCORE: '20'
      NOTIFIER_DB_HOST: funds-db
      NOTIFIER_DB_PORT: '80'
      NOTIFIER_DB_NAME: funds
      NOTIFIER_DB_USER: funds
      NOTIFIER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: funds-notifier
    secrets:
      NOTIFIER_DB_PASS: AgCONT83+GJ2WLiqTCM1oHN4ITW3Qap9a9+NWxJXVyQglTvHMGz/+CldB0jHAP4EIgmF8IQNNL2geEMUKzNIHmBMFyTpxlM6jSz1Wkk1uf2+88qg5qNNUQNm3lZLCSeH59HN8i00CWlrYTtKGs1tx/p6IjaeMJhYXKArMWiwpkRalT+W8xpYo8Vu03bbhT0vcMWTwheraLOlUdaslKoXr7IXpjCgUCkWbhK2SNMaHbX3UHZ0dOsT34v84Or9JVxsNuj4TAoR+P/z5/BGbnQgESl75oUuZHEZmjePRm4DPyXNpnHBzbdojbzAxqC4MbIPhdoB6V45/V/RC+/zTRxV6hxPZI4QBkTMD9VmXy6K4wyZA9odEK8jKjVQDXh9eeu303gP3zAVF7NO58KsZU95d/Vqt0R7W5d3Yj4MhMas7eN9k6Eo9HsBs56mvENbhSODkTrSLDdywJeI48jjojyivq5GVm4yM2DM6gM0LLkUnD3bQVx/BZuX7X6jNZ8OlSnHQwNiCrcqgwL5KgDzIUTjWo6e7BPVKXA58HZOvgSeu47cFsQb777balij4DV2YXbS35U4WPzm3luoQsPXknzAkFzuVQDfnCGMjpJsuOJ/5mDmtuvL8fqOvTZPNJNm75VWXHJfd0eZCv9YNvSasIjB4bx2m3Zcpyv2RjwUMXMzkVE6VttBFHPNHFIziQu7J41CATv1Pq3QQTQIkl+VslurMB5/mdIwY86kdGHFnwE1vFloLpb6LBlN7o86wy46ePmMMaZPqQd/Vx0Waga2mzw=
      NOTIFIER_RECIPIENTS: AgA1sg7pXOvjsaHuu+kwmMbvuGqzjbVqvqqVVi+CRdy4JPB/49srXoOAXX572vZ6S0We6ROMeof2gMwU2jxLETiELPHVK/ATuU/laYUPAKfpYKF70XOjM1AHOfheYF/abxqad0sy195ET2tik+UXXxSu5WP7vNFqwZGHljI5C6siW9REpIHZuv2UzKg8gzd/70jnOpVEK0cRXdu51oToWLo2KTeW2hjg+dBN0peS8dZLOW3V1pTdxk9A0TPH0s1xvTAJ3VrOITTr12od6hY9OPRuDZY0OlIOGssVSvsLn/Uhpdt/y6NgPSmqJtBfoDIzhA1Tymc2ulqopuVhU0OTNvXMxlOn9fqiTA4IfSCvydvCz+NFxAhsTPvgYoLov2PhCPmhAuFkByXv8JEnY30deqIq4P0g+myuyHGD93RqQRvUbUySVXGCLb6OIvmy9wWypP2tHjveMSxl2cvw74CjJmwG957F77mRlCWxv3Y6a0NDEBTbtyqYrPRMnajpSTyNCFQHvWTPySWxzTv2f8VM6+CbRqAidLN9paWWVG0FuDTPGKasGk4vZ2R0fWT3P6v7YYJewDLnUX+VfC/M/HNp6yRGBVjnza82O0wBXsrmNOViAnkEIBhLdnm3ZPlA/+LcW9KA3+RKHCF70AntUtS1dS7phIFby7KQUOilkAsh84yRnCxZzwwwpdX8MaTQhDzUUpROvXuUYO6PChsB1sONBxADXRfFrWLRWxE/eNizu2p6dOgiyGVB2r87
      NOTIFIER_MAILER_URL: AgAi/ype+88MYAkzUlR2W3gAXVLMlulz5c1tbuyGEI0j4E//DFmKvQu289b6HTKy9Fie+c1jylX4molpKCxYO08+nWBDbiQLDs26oeV3c6wlYxr4m2urjJp6cUXRBdiRBV3KSThREvZjxUK6aIbBXkfqSq6WXFHXfx1DPgfMzDEPYQMpHB1VuFJRD81jbDqTNXaZ+Y2M42f4Xwfdt8+icFVCJc7J60KR40C1mlnCjW9gMm6Y6lwWW4YerFfk8Su3Ul/bkuMIDHVJ8rDhXBfMUDO5f5iEViZkJkFFP5vLRlucGGeqS7qt1+lolkv/M2GU8UBzASb1Vcmb8kErC38NxpKhSoSkTy904r37eVjVuZk1uMEHJJE1NxW3Sq71CIpT6qzcWSqE3nurrj3sgbQo34HDjzxz1aTN1pOtSTpRyB7PHd+TvBGu9DNOgO399D8akzHpm2SjEzWqaBZ+e+woRmogq9A2EnKsg4qXllg7VVE9hfLb9VueUDIxkRdCLNuv1kt5CnFs3NWRBs8RcAiBeAa7TYA+VOwHPvv0HCJlD+Gh2MvWzuIZL83qnyO8ZqDihiJWtVeptad4LukX3uuuWEfX4NwpI66zEulL2+3b02PTpJgooQhiafyICHf5VwHK1BcRPzpdkduzuQNz4rBeLF+9sAmu2hVhOXQF2KOdLtxrJpYBVGRzkjQrX3zM2vYuD+yky1LZECvcITBIoPCpXGDPqnb08fnp9Mz8c2CFv3zOII11OAJyKEhLS33U4nm2A+jHpTA=
    containers:
      - name: job
        command:
          - /notifier
