apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: '0.0.22'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds-notifier
    schedule: '0 8 * * *'
    image:
      name: vibioh/funds-api
      tag: '202206240715' # {"$imagepolicy": "default:flux-funds-api:tag"}
    config:
      NOTIFIER_SCORE: '20'
      NOTIFIER_DB_HOST: funds-db
      NOTIFIER_DB_PORT: '80'
      NOTIFIER_DB_NAME: funds
      NOTIFIER_DB_USER: funds
      NOTIFIER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: funds-notifier
    secrets:
      NOTIFIER_DB_PASS: AgB09bp0UKbpqMGmbduebyFkZBy/AzanWa7quOw2yA9c8v7uJf1EYi+JZxvzRuJxMSOcZXwvqgOdSdZMr9zq47vOQZPyXT50cZj2e616vmvfR0EjeXXad6BOXXmyc5A4x1axrivfOZcX+RdwS96DTYDVEBsMJxi+iSazXviOoovvsjYHye8+w580INivvfTKrbc+BC8WXzoC0liwDqPWBtDs0t8xo0e/UqKDbalCncSRZqKvfNNb4SUc04IadVUvWcFOYG5UpYIM6M9Acs1soN80H6e7zbrdG2YIozcMJI2hy0LToKsVT6GwB4AZS38lWTQNAedJVtSfq7jCUGuOsx39bT2aIabP/iqHyKLKJtYgYF1vy2SuPFO9ndZM+WDLMjHCgxlOKX5MGOCRaOG2yelixFY3hJsHQCvlb9YuBDXO9gMsvbH6lL38/2luGVHFg1x2G8l6ewSqiWsZC1cLmQTBtSjv/GZfQVGmNsb4rRuo67yU93EKaeqc2mqZXqpr7qcrkAQUeghHnYwIP7rhSoAxObHo92htRfkcVxUfR1yZeQm2lc1tfksxwEZFiLSEzDyRJPNBJaX+OqLa89oQr2may6CKQkRGtA7WpAz/RAKQwuJDepg4xABlM9AXdeopW8gxXR0mbkx2InJIDb2rOgC3bnvjl9/vPIRIhXr3WbGKy3BajUFrxMUqdAxEMcX84n+GIRGDDXjpHPha/RfZFUr8CvCdKTLFcNF/2OM8IXj5/uUGfRd82NDKdZQb9llx/u4z1jMA2P51Wt67+jQ=
      NOTIFIER_RECIPIENTS: AgCrLOpJPIe7sWJQvZsOn593kzeg1OTPaOh5ZxcZ0EpcWisZst8ycGeay3LiT7Ft9WqBwu/Mjl5xkaHa2EaSzmTkpzuostDMDeVyo7GhM4QX0vzpFdnHoHFN0SBzLpUZvh4E3I7QEspr5UIat03GC/+oN79tmwThPZZrvx05/w4GGCYlPBHKPe87Gt53pSLXs5tmM3i+GHMScBkCFJsGxlO89HpPCxq67+01LmyUqQveHK8T3lcNiGkUtQJzF7lEEYBYo2vtrLkgCwG2vY80kp1US+HNrWqUnbvt++bq60QBku90MzLNABRLwHLPDWcolFDlUJFR8uhdQaLXWTHDDaPd+h0Ueg3junP35crekxalQ19u3sRH2OgaFz8ZQJtF5t6zeErJK38fUKIxot4+cWyEwk8ucjwj//vEOxzAISlFLXnz/L8VMc0ej9gtdY7tUuEsRnGgjdbCM3KXCjKtrHvtjyPvAPOybyOTIcUhHssc5uQNvu6hYaDJ0wq+y15FzVnWqy/6WGXRqmPMoVea28CMxYQOmEnlU+cTvFDwQXlf3q7NCFsPvwpk99lTNo91KY/W8Jrg8BGqtzFsVLhqcBIeFiZH+ZeKbmmeKHw6t4l/nBNd9CnyfNYQ3gQL+7hss0VFlkMbWqe3uKTJ2PdsjbkHr3+Ce0EGtelyD479oMMzIDMp43FshvoVJMBYp/FajsPnyjmfyXJd9qPBa3TB6pq+rZaoVyH8ApzKpRn9+JCm4jK1NKLUToFC
      NOTIFIER_MAILER_URL: AgBJWMiXycbGh5Qah/1YM55Qc15Sz6q8aRwA6r6mDGw60ATKOYUffO4UydFlxkBuvLNuLGIlj4IiCd+E2JwAvpoOfqLxwRHoPcsOOD5hYyMO582d3x5agaR2bMXxPE+jRJ5ZDh+ZAqrRbaTdxI91enXaPeS0rmIMFAXS0yEXvDJl4icBDGncsSXmrlRY33yLpL41e6dOxCJCOwH+QzyX5c/SzYYfkOpPjCevXX0nLUtTAp4O7oc5PEJ6pfpFhlCnjLib1LTImZ7LTHIozY3qDT5iiEO/U+JoxCN4hvX3RG4f5F7q5jpQaSXiXk7FtG32XQISe/xUHuev09Ggbg8SIqlefAQnEqTRPcD57jtnjUAIIgGozQt664qztCjRGHyCpM5d/taSIsfOF07BrYTInonZZJSQIU9HZ3ZJIFuHoKJ0kjTUeCJttzn4DlgXBYAY8c/2WnR9sgucKvb1Ptew6UAiNyMonRxnHm12s89vW8q7POGUxcl/3rNW+DoOpwRoz+uDc3ao2sWi0bc0RBlqwNHiA5O3qTGMOT8smBuGS40opH1lKOJu1vIq9aIssks5LpIg8Q+5boyTHOCxz0FC+WzE/8z++jODDcPjGBdvLcx25iKZRS6rJoWezxVLddebBM+4oEy3dJMUsbzun5cpPPVbxxRNoxTgC8J8xg3P6R2oNSHDwvcIUjcDbNDkTOnkWI8246YfNMk/nc4LNtaXBt+QOR9rKnJZcZQjaGO+m7Xf5yqHl8SghHd+A0qST7H71xA9vjE=
    containers:
      - name: job
        command:
          - /notifier
