---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: cron
      version: "0.0.8"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m

  values:
    nameOverride: funds-notifier

    image:
      repository: vibioh/funds-notifier

    config:
      NOTIFIER_MAILER_URL: http://mailer
      NOTIFIER_SCORE: "20"

    secrets:
      NOTIFIER_DB_HOST: AgCnm/gda849hFYrwZLXWpdSe5fxaKsXHb73tXeqvuQCW9DbGR2qv8d6GNrEjnc024Bag5IXVpEvmL/PMkEJ4jFBY6rQKB171fcNkDQzG/PBqW2BjAWwm8yjkeUG4qgjyrW3e5W/JRvyzVTEkvZIRVw8MM6ONzXKUPrlylVgEfr89wdOfnJjanfYgmQ4yy4Qc0+2Q4fC1vz1BTczCxoD2j3G764WtODLLjPOmpCCn8HmVeTt0yo+1eiwahSYxyQSjpXncXFziZDRW8dDtOmcBgiuip8XSpI0w9hTbWDGhjqkb0fj44h+15wq02ChZSBEJ221bkJ2cMcSS9Crj1XnmLUH2ishm4cAP9FIluURq4q/EHAlfipjBo6wCtQvJD53kOIauTtVBjgGGjWA+tMuYLxD8MBkABbz51b1Rwnuo20dhhG6foK4aV/oKp3XBkCAiumTNnoIjTlRr8c7MbAYxOZmnqy4KunKuQNSps3ewtqOmCsCqEwLyMHy8YFt7k4F1O2mcsUm+cLFtfXlr6oIep4vYrrHlSF8MivaY4ctKUjgOWAkb7vG4w9ULq57y5e7S20iclhqF4zSnTI5zRK+0Q/SxBnxgz8cE9F0HAwISCqHyg15HPWUDXbCc3Z+ss76qTyAAKyskxMgoCc9LoN6AvXpfnFIRPHd9yW+l8Kpra0rC9lWhdf5gQ55MKERCjgoAjle+xq79oX3HEDS+h4OWYhmcvmxUI+0
      NOTIFIER_DB_NAME: AgArMPWMHwY2UF8hf0fy8+Dzl1l5jD1SUGEUzsT3Q+abow28b3t6u+f3HcWTAaswJi3vlel/kmIzOhvLrIvViG9fMDhWeeg8FdZ7NX/XhhhKCIBKO8LLUe2napIENcNQZGER+LYs8JT4XGw24WgVUJ9zrdlrApsJGpISPKAdGL5LGIH5lONNtUx3qD9OhIVWpsLKHHnjQ4bMbvxKoezzaYuzVytj0/Ov0+gv9/V7D7fcZ6wzbW07r/kFAc7xDqYmfD1FhRuFTE1Wl/rXPVCAePirJbxGdcTRwMhj6qS8gSxzE8rSBotoZYcGm+RXiYoYyifjpV0VfEhfi5LY4HwSrjURfV5Lsmqt8h6xjRrsWlPM0CVfw0s3RFfLrFv8BnMAkljFYzZNtoCXffGD8krfySNqIj87cQmZYbwan2pN0Wvlf5jOPna5cxSLaJ9GPd/tBWsyR5fEjVcFUX1YW1UaZ8VZpM0MIT8LlADhheLCziMcOh1YtZv5SZvG18lDa7lFzAVRi3Fd0YGX70vSgGt0HZuztfUPY0Hx+Lz2ZMTuqzKuf0iOzgqebO64sXmwRY2rWHzCYFyEgvGDc2U/G0ZUHwJCUdl0gIvXXrnew44pkLOeXyRp4f42azfa/FRotDKEuZderu5CWhgv5H3kbXFqc+n1nJhpTDs0k7oE067oJj8lE0edLHoWPhJlyqFwgHQhXTZfEeb7xnZvqw==
      NOTIFIER_DB_PASS: AgDM+mEVyvPGAKNUbxn73675upvblEW6mvRoA8OCR8hivuEvFipJIxoSj9gbJVAr3ZTypJ2Q2o0xXtCj6hJI5OOjXWhoF38q49U1diJkdmnknPu05YbObjjH6LalBdkoxkJR5FW7cOha8U4B0M0TFEs4SOqI9A4wycg4u4mA/VtEZjbV9bHEjr/xrj7aKejvzbOXkpgJfLb09+y6O7oeE1RyHXTqPLlgpUAb77gTfRYO9pQfDC01yqaY61NXPJDbxhFrG3QsLFqTRT7uiG0zBepjwli1qxY3+QQs32JCYhJDACFUR9CAy27hUvuCw+0llxWMP2iNPNc/2fYZjweZgB62hyoe+6E+L1mJS8VE8eEVjwFYceryoax7CppD1h41rf2aT8oKpeSpoTsXWl8RD059fx9Th37cG6ITyqLeLg4MKFBWnWi0sPzSBkqKgH+TYZrjKp3nXE7rnbnrgdB7YqbJfn10XS0nHpbAMPjSlYDoA3szBP9UQhzMgj9f67nJ/3RnPN8Bl99+gQ8fL0/4uy6nP+14x9F7Vn5sZVklydTtnV5BVcmvhUW+lX8Xt2cji7nIFNIIVJaVGJqcEl+iEzRAS3EFJybzquyzM9yqfGWQ6XN2/3fKAD2sxftVxA26qmgSZ+v+IqAjxcWY/adVKh/f6qgs7cAQZ6bc7UVFOZ0qV1nicb2gp/XQd4cHpWImCijJFe/8ziFB61inp8kf8MmlQZWt2Id0IbwuYhFpKoW8VQ==
      NOTIFIER_DB_USER: AgB3qUlHUPgjhfDA+LI9oNjV9ei9DAoD05aA55tWZNhcL2CNq7Nn/N+zlFQdNjujiPuPL9GolTdMaHXH15j/5pGwksMiIOw2EsF3FRzvKlE6X7hW3+2INdqgwH+TGyvwcVi+7f0Gd8yuEM4HIJP6A8+ynOk2z1Js3I9LBMCfSFZPh/sfu514dJHPd8s95Tux61lKvqSLa1tchkwC4f4uaGVGsYE9s3CnjqHVGYjAouBBWxpyWsYdyUhj/FZ+KS1nsfrjePC/fwJ7wN+QutpwfoblnnNxG4TXTMfreTV1tPiPs/yiYHHseC2wjd5IXKpCb6F22zXSf+O8KkfOu9JDImJ/O5KsZsPBNLDShHZTJ8lvjgDW8VgYL9fFOHhUnFO2dTHtQWtc6aUsLP5Zcr5F9yRN2X7eZAtSdfnbx3ov8CFmEZdO61+7elBgU2sknkNJeSixI8i4VgEgQSENviihcgFT3exzN5SJOJY1l4gu72wIprm+B4BmWTBCvpCiKmmTVTm2PVuU2/b/QybbxweoQyH+cp2ZJVI99VUl+cAeixQnt0K6I7YtdqWP+92XRCQbVurNx+emEWckOTjNUb01YlypUg9hzNSt7r0bdqg3fB2AL6IhnIxNvbntvJyPvdtddD21wB9AHj5XEgvKVJS916iVBC5Y250bvMTP8oS+2ch4QHMjBIe2ObBBEN8GAxZFbqFquVXbC9r3KA==
      NOTIFIER_RECIPIENTS: AgAGqCu9m2tVU1MmDNY3afoR/gkyoKvtFsMXLaTrzROsT1OL75K82zh+EJ7va2h159lWHfhRErqpOMyFEq30TYfTWYDdk7/tCKeBraJOUlnXRC4aNqJzy6OBZtzcPLHMfvk7A99NqRJueIkQHLLSp9IqbRl8V/75eKTafEQDFSp5q9R9YQXub/YJGjJWBCD7pkZhzpbUtPpddovVH1mL2BtBXFPR96QIPSq+ZPnyBk5rKpsRZr4LTwHT5koo06fJ3IPK9x6SE/G19IaBhhJYTjVZ8j7gDUrCokg75m1ERGliUiuWSaIgcqjMNyg/h+OPjD6okT45z2xOsFgbAnKIT6oKeO5svHiyrBxMw+zqcpD3emhNyI21T05FlFTgMQ8IM/UtYS4i1NGP6Gf+L+rAiIxz1Nhhe08fPnT8dpQ5/GbODn8F+Cuw7of7/iCS/dnDk28sK8PHBYOsyZxLMM5XSXsJRHGYgblQz2gUmr475YY6E6OuMwj/tHTJZmaUpy9ZbInCHvNSg3TQLcY2a2IfF4andPVk9T3JDi1dmQ1lF8lpWhfEdLwoRP1IWAF9vui3PyniA0WKcMzJ/G1exuUCN702qyc8NCzEKFrtgpIqDaT0ApUVA9+U1Cc5RvY3pUI6SyWLyTNBrru6dL9+VPMDcAStONExAZPfvDsHR7qMPdJcy3+G2EdbEV2dPEo9oEXZbVuPsAfi/4PMctEbSxl6D2XTvnWb14S4rWCASQL8QRTQAg70vJo7dKkZ

    containers:
      - name: job
        args: []
