---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds-db
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: postgres
      version: '0.0.32'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds-db
    config:
      POSTGRES_USER: funds
      POSTGRES_DB: funds
    secrets:
      POSTGRES_PASSWORD: AgBv0gNIAdx36PkyCD9KYDQIVq0+rD7XvclD/BPMKlXrOas23Hos73o2uWS3N01h/BW0AJg7uJ5bxzs5az2VsCRbBAO7jxBvtsX0X1FWY416eJk8ZwF02i6e0Q+KhEZyjoB6VzyUD+UHS+5uzePiy93bYbllNwxTmVK51eMUMJh8HxQrJV9Vc1wSnZ1N7TqWJ5MMYBqct+PwXtOM7uwRmaokD08XGs3LA7VaxntaDwiC5vtxAx5OB401j8maH3Iu90jK1wPKn7GRTB4UL6rcvtykYD8P9nDDSgCC2X0VAgcI75wTpHcxmHa9L0zG7sjDV9d9Sob3fC8m30iOu6Y2nKSoaU+mZgXz4ykcGVRFwB+kgbkDv/r76lj1pTytfvRgCzs8FP04Yx31BGTY1zDvyRFSeJKteT4DKFrNNGwGQSUftFT/ii8WWbx7kn/UlLW10fsya+oeCM6v7xvCK3HZbkpAvMqQXEiCh+m7zEh9i1V35y3ZPu/8T0BJy/e3Yc1Xih4PzdiW1yIJqWktEGaePGCubpg4ocl3pFZfuCDSpznwPs/bIEtR0x6kqSAf9i9OKodf3KOus7AZZibboT1ARTad92r5GFLhsB9X/wK71WwemCbm/IiR40NLRXRO3u/l0m3XuXTQgBrEHtXNwjdolbq0RZ4uIG/q1fTVtir4by/Lkl/00MtUD0sy6se1+xy1zOk1OPEoPdxxqaoSI4mzw0083X4O+a7oBudKz0awwj/0wJPXum4qanZX/1uHy16gqbTSvS5qt+HKt+zZMuk=
      FIBR_BACKUP_URL: AgBi0zpwBu4zOibraOm2MJSJ7aDl1c5ooYDnBW0SsSTPEAU33e5L42J7Ayd/UOEIiC2+wJKkvsbTza2W8We9moknI2f1CRaNF4Jbg2WEZdmD9f3VgP3WgBopL7G6DGDrWJp1q0Jq1cDw7KSzUIpyfSVDyYzeLWhoxIqm1brQh8drl7TdHKhp+qJv+5d+JKrwqF6/GopaoaIHlEv7kkCChAtY6U1chxbjrrwiAE1Idqi78mRa86TNED0bM7L73oFjMbughmusnJt9uEeyMn4MyoGNpRIKs2VCncETZAO55HiX0Rgt4WdqI+0Jc3xd9yx7wZbJbLMZc/XylRCwjwaMnKxiHGLjhXjdYdKwWgPv8ebbnNnqdMM9Q/yY2Twlzd3NWQ3Z8Pag1gUd9U2fLDkWSjKBD8WBxGvZDhotwOoQKiM60xAxsryarm2Nm1kA3/KE91+6meMPyoSiOvhY101KUvUsPdlxM2uIefsWvJkmO4PKeUvPkXtMFFXAfJo/cmMpd/eVittbO8mCXKxscrWY6EddnH9k3y46lZYv98dp2s8yP7N+gyD0pVfyv629FgDWrPnXV9YQyYqu9ytk/DTM0y55xT9ibcv7kTJfoQiusFnjnR7mQBZ9jRUcrsIrSGeqxxNihnaPmTP7i54bVbgW9zZFU3e6fVq/YudY8iXb9tH7vTCRLWal35gF2Y2ezTmormvfzyWPPKdvamF9JPPaxWa6daxX22mgqv0ODJZs0BTflQ==
      FIBR_BACKUP_PASSWORD: AgBjJznrhRr41GuKx9VhmPY3poM31kkywR8stMrwyXcNtxHVo0ggg4anXrvHMkNWnQRst2LG6AaO41bfiX63Nv8fA1fNvL6UF/EjNzsUHBPtC7E/VOu59P6FKWevQuQvQfIiVloIkuBsQptcyZyduMYViPVP5r0Dtf9WUlv1Sp2OSx1gucVMQeojF9xaF0V+O4MuQPipFmDEMIpIp6xwNUKv74BLMyQ8Solwe/o+/+r/8vRUaNpJYK5IrHcmpqnw9StWss4iLFAfRe/eFkknOF1e6PSBObAc0v7CZyBD7SnJKHGdDdHBcjLT8OqxvtqJDKhJW0Pgy+h58sJGhZB1WxbsuLWh1KsnvofnhPN6syMnKSiax/4yfBy6rJj9tVVAEc6wyW+7vURKiNyFliEBsaNDp5mDXhiF/G8XLuglbR2HgkX18I8lQwRBFItB6iKLkCviJ7MrotG2qyjqvKJccE74Eu2xUubeung5tqMa6Ygy5nY4fjKkgrBE9qe6NiD6QFUXxCbBNBdn8z/hIg1x1dg4oX6KuxzRtkXp3RAJKVcJlykog+0ABilSr9nCwvXN6LKaZIRanybFf39FuDv5QM67rqiiTcte0utGyl5cgKQGkqQJU2oEEvDS4+hafUMukPy4tPEyyoRADoquxqvOCNfaFh9equ0Psp7zcyp10RtPxXeKUFPsNzE7G21ncF4GkQShGvF+m6ZcNH6DVDda1TMNVIfKWq8Uo5l4EULUFJWI6BMVsEVCjVO90DitVHIInHsiNSIkg71Fd6rs7cs=
