---
apiVersion: v1
kind: Service
metadata:
  name: funds
  labels:
    app.kubernetes.io/name: funds
    app.kubernetes.io/instance: funds
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: funds
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: funds-api
  labels:
    app.kubernetes.io/name: funds
    app.kubernetes.io/instance: funds
    app.kubernetes.io/managed-by: kubectl
spec:
  selector:
    name: funds-api
  ports:
    - name: http
      port: 80
      targetPort: http
