apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.46'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  install:
    skipCRDs: true
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds
    image:
      repository: vibioh/funds-ui:202102211154 # {"$imagepolicy": "default:funds-ui"}
    config:
      VIWS_LOGGER_JSON: 'true'
    ingress:
      enabled: true
      hosts:
      - funds.vibioh.fr
