apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.81'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds
    image:
      name: vibioh/funds-ui
      tag: '202204250738' # {"$imagepolicy": "default:flux-funds-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
      VIWS_PROMETHEUS_GZIP: 'false'
      VIWS_GZIP: 'false'
    ingress:
      enabled: true
      hosts:
      - funds.vibioh.fr
    canary:
      enabled: true
      url: https://funds.vibioh.fr
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - funds-db
            topologyKey: 'kubernetes.io/hostname'
    pprof:
      enabled: true
