apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: funds
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.67'
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: funds
    image:
      name: vibioh/funds-ui
      tag: '202105032003' # {"$imagepolicy": "default:flux-funds-web:tag"}
    config:
      VIWS_LOGGER_JSON: 'true'
    ingress:
      enabled: true
      hosts:
      - funds.vibioh.fr
    canary:
      enabled: true
      url: https://funds.vibioh.fr
