FROM scratch

HEALTHCHECK --retries=10 CMD [ "/notifier", "-c" ]

ENV ZONEINFO /zoneinfo.zip
COPY zoneinfo.zip zoneinfo.zip
COPY notifier/email.html /email.html

ENTRYPOINT [ "/notifier" ]

COPY bin/notifier-arm64 /notifier
